// src/pages/Profile.jsx
import CardList from "components/CardList";
import NavBar from "components/NavBar";
import "./Profile.scss";

export default function Profile(params) {
  return (
    <>
      <NavBar />
      <section id="profile">
        <header>
          <h1>Perfil</h1>
          <p>Jogador,</p>
          <p>
            <strong>Você tem </strong>
            <span>4</span>{' '}
            <strong>figurinhas</strong>
          </p>
        </header>
        <hr />
        <CardList />
      </section>
    </>
  );
}

// src/pages/Profile.svelte
<script lang="ts">
  let cards = [{ nome: "tem nome", selected: false }];
</script>

<section id="profile">
  <header>
    <h1>Perfil</h1>
    <p>Jogador,</p>
    <p>
      <strong>Você tem </strong>
      <span>{cards.length}</span> <strong>figurinhas</strong>
    </p>
  </header>
  <hr />

  <!-- {/* <CardList /> */} -->
  <ul>
    {#each cards as card}
      <div className="card">
        <li>{card.nome}</li>
        <input type="checkbox" name={card.nome} checked={card.selected} />
      </div>
    {/each}
  </ul>
</section>
